version: '3'

services:
  web:
    build: ./docker/web
    ports:
    - 80:80
    volumes:
    - ./:/var/www/html
    depends_on:
    - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monolist
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
    - 3306:3306
    volumes:
    - mysql-db:/var/lib/mysql

volumes:
  mysql-db:
